[package]
name = "klepto"
version = "0.1.0"
edition = "2024"

license = "MIT OR Apache-2.0"
description = "a general purpose extraction and data scraping utility"

authors = ["James Hunt <jameshuntdevelopment@gmail.com>"]
repository = "https://github.com/jameshuntt/klepto"

[dependencies]
